import type { Metadata } from "next";
import "./globals.css";

interface ChildrenProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Desktop Project",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang='ko'>
      <body>
        {children}
      </body>
    </html>
  );
}
